### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by dhnazarenko** [dhnazarenko/timeonation#3]
### User Story

As a User,
i would like to see a login page where I can enter my username and
password and then come to the "start page".

### Screenshots

![Bildschirmfoto 2021-06-15 um 16 30 45](https://user-images.githubusercontent.com/82373303/122071499-105bcd00-cdf7-11eb-9d17-73620be77258.png)

### Tasks

- [x] Welcome text
- [x] Login text
- [x] Input field E-mail
- [x] Input field Password
- [x] Login Button 
- [x] Sign up link
