### ISSUE TITLE
Register Page

### ISSUE THREAD

**Issue by dhnazarenko** [dhnazarenko/timeonation#4]
### User Story

As a user,
i want to see a registration page where I can enter my details to register.
If i have forgotten my password i want to request it again

### Screenshots

![Bildschirmfoto 2021-06-13 um 02 28 05](https://user-images.githubusercontent.com/82373303/121791887-08c9d780-cbef-11eb-84ad-b37a9c72cd96.png)

### Tasks

- [x] Backlink to login page
- [x] Headline
- [x] Input field username
- [x] Input field e-mail
- [x] Input field password
- [x] Input field confirm password
- [x] Register button
- [x] Forgot password link
