### ISSUE TITLE
Forgot Password Page

### ISSUE THREAD

**Issue by dhnazarenko** [dhnazarenko/timeonation#5]
### User Story

As a user,
i want to see a forgot password page where i can reset my password

### Screenshots

![Bildschirmfoto 2021-06-13 um 02 29 13](https://user-images.githubusercontent.com/82373303/121791902-2ac35a00-cbef-11eb-933a-eb2f7ffb9ec1.png)

### Tasks

- [x] Backlink to login page
- [x] Headline
- [x] Introduction text
- [x] Input field e-mail
- [x] Reset password button
