### ISSUE TITLE
Search Page

### ISSUE THREAD

**Issue by dhnazarenko** [dhnazarenko/timeonation#7]
### User Story

As a User,
i would like to have a function in which I can filter by categories and locations or search for terms of my own. These should then be listed with the main information. At the end of the page i would like a navigation
to switch between the main pages.

### Screenshots

![Bildschirmfoto 2021-06-13 um 02 30 10](https://user-images.githubusercontent.com/82373303/121791917-4f1f3680-cbef-11eb-9f6f-170da2b9b80c.png)

### Tasks

- [x] Headline
- [ ] Input field filer categories
- [ ] Input field filter locations
- [ ] Input field search
- [ ] list Project cards with main information
- [x] Navbar
